spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    database-plinatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      #不加此配置，获取不到当前currentsession
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
  servlet:
    context-path: /series
gt:
  maxzhao:
    boot:
      #主动开启多数据源
      multiDatasourceOpen: flase
      datasource[0]:
        dbName: second
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf-8&useSSL=false
      datasource[1]:
        dbName: third
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/db3?characterEncoding=utf-8&useSSL=false
alibaba:
  sendsms:
    SignName:
    AccessKeyID:
    AccessKeySecret:
    TemplateCode:
